# Relatório de Análise I

## Importando a Base de Dados

In [1]:
import pandas as pd

In [9]:
dados = pd.read_csv('aluguel.csv', sep = ';')

In [8]:
dados.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32960 entries, 0 to 32959
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Tipo        32960 non-null  object
 1   Bairro      32960 non-null  object
 2   Quartos     32960 non-null  int64
 3   Vagas       32960 non-null  int64
 4   Suites      32960 non-null  int64
 5   Area        32960 non-null  int64
 6   Valor       32943 non-null  float64
 7   Condominio  28867 non-null  float64
 8   IPTU        22723 non-null  float64
dtypes: float64(3), int64(4), object(2)
memory usage: 2.3+ MB

In [11]:
dados.head(10)

,Tipo,Bairro,Quartos,Vagas,Suites,Area,Valor,Condominio,IPTU
0,Quitinete,Copacabana,1,0,0,40,1700.0,500.0,60.0
1,Casa,Jardim Botânico,2,0,1,100,7000.0,NaN,NaN
2,Conjunto Comercial/Sala,Barra da Tijuca,0,4,0,150,5200.0,4020.0,1111.0
3,Apartamento,Centro,1,0,0,15,800.0,390.0,20.0
4,Apartamento,Higienópolis,1,0,0,48,800.0,230.0,NaN
5,Apartamento,Vista Alegre,3,1,0,70,1200.0,NaN,NaN
6,Apartamento,Cachambi,2,0,0,50,1300.0,301.0,17.0
7,Casa de Condomínio,Barra da Tijuca,5,4,5,750,22000.0,NaN,NaN
8,Casa de Condomínio,Ramos,2,2,0,65,1000.0,NaN,NaN
9,Conjunto Comercial/Sala,Centro,0,3,0,695,35000.0,19193.0,3030.0

## Informações Gerais sobre a Base de Dados

In [13]:
dados.dtypes

Tipo           object
Bairro         object
Quartos         int64
Vagas           int64
Suites          int64
Area            int64
Valor         float64
Condominio    float64
IPTU          float64
dtype: object

In [15]:
tipos_de_dados = pd.DataFrame(dados.dtypes, columns = ['Tipos de Dados'])

In [19]:
tipos_de_dados.columns.name = 'Variáveis'

In [20]:
tipos_de_dados

Variáveis  Tipos de Dados
Tipo               object
Bairro             object
Quartos             int64
Vagas               int64
Suites              int64
Area                int64
Valor             float64
Condominio        float64
IPTU              float64

In [22]:
dados.shape

(32960, 9)

In [24]:
print("A base de dados apresenta {} registros (imóveis) e {} variáveis".format(dados.shape[0], dados.shape[1]))

A base de dados apresenta 32960 registros (imóveis) e 9 variáveis

# Relatório de Análise II

## Tipos de Imóveis

In [26]:
dados['Tipo'].head(10)

0                  Quitinete
1                       Casa
2    Conjunto Comercial/Sala
3                Apartamento
4                Apartamento
5                Apartamento
6                Apartamento
7         Casa de Condomínio
8         Casa de Condomínio
9    Conjunto Comercial/Sala
Name: Tipo, dtype: object

In [27]:
tipo_de_imovel = dados['Tipo']

In [29]:
type(tipo_de_imovel)

pandas.core.series.Series

In [30]:
tipo_de_imovel.drop_duplicates()

0                          Quitinete
1                               Casa
2            Conjunto Comercial/Sala
3                        Apartamento
7                 Casa de Condomínio
16                    Prédio Inteiro
17                              Flat
29                        Loja/Salão
80           Galpão/Depósito/Armazém
83                    Casa Comercial
117                     Casa de Vila
159                   Terreno Padrão
207                      Box/Garagem
347                             Loft
589      Loja Shopping/ Ct Comercial
2157                         Chácara
3354           Loteamento/Condomínio
4379                           Sítio
4721                   Pousada/Chalé
6983                          Studio
9687                           Hotel
23614                      Indústria
Name: Tipo, dtype: object

In [33]:
tipo_de_imovel.drop_duplicates(inplace = True)
tipo_de_imovel

0                          Quitinete
1                               Casa
2            Conjunto Comercial/Sala
3                        Apartamento
7                 Casa de Condomínio
16                    Prédio Inteiro
17                              Flat
29                        Loja/Salão
80           Galpão/Depósito/Armazém
83                    Casa Comercial
117                     Casa de Vila
159                   Terreno Padrão
207                      Box/Garagem
347                             Loft
589      Loja Shopping/ Ct Comercial
2157                         Chácara
3354           Loteamento/Condomínio
4379                           Sítio
4721                   Pousada/Chalé
6983                          Studio
9687                           Hotel
23614                      Indústria
Name: Tipo, dtype: object

## Organizando a Visualização

In [34]:
tipo_de_imovel = pd.DataFrame(tipo_de_imovel)

In [37]:
tipo_de_imovel

                              Tipo
0                        Quitinete
1                             Casa
2          Conjunto Comercial/Sala
3                      Apartamento
7               Casa de Condomínio
16                  Prédio Inteiro
17                            Flat
29                      Loja/Salão
80         Galpão/Depósito/Armazém
83                  Casa Comercial
117                   Casa de Vila
159                 Terreno Padrão
207                    Box/Garagem
347                           Loft
589    Loja Shopping/ Ct Comercial
2157                       Chácara
3354         Loteamento/Condomínio
4379                         Sítio
4721                 Pousada/Chalé
6983                        Studio
9687                         Hotel
23614                    Indústria

In [38]:
tipo_de_imovel.index

Int64Index([    0,     1,     2,     3,     7,    16,    17,    29,    80,
               83,   117,   159,   207,   347,   589,  2157,  3354,  4379,
             4721,  6983,  9687, 23614],
           dtype='int64')

In [39]:
tipo_de_imovel.shape[0]

22

In [40]:
range(tipo_de_imovel.shape[0])

range(0, 22)

In [43]:
tipo_de_imovel.index = range(tipo_de_imovel.shape[0])

In [44]:
tipo_de_imovel

                           Tipo
0                     Quitinete
1                          Casa
2       Conjunto Comercial/Sala
3                   Apartamento
4            Casa de Condomínio
5                Prédio Inteiro
6                          Flat
7                    Loja/Salão
8       Galpão/Depósito/Armazém
9                Casa Comercial
10                 Casa de Vila
11               Terreno Padrão
12                  Box/Garagem
13                         Loft
14  Loja Shopping/ Ct Comercial
15                      Chácara
16        Loteamento/Condomínio
17                        Sítio
18                Pousada/Chalé
19                       Studio
20                        Hotel
21                    Indústria

In [47]:
tipo_de_imovel.columns.name = 'Id'

In [48]:
tipo_de_imovel

Id                         Tipo
0                     Quitinete
1                          Casa
2       Conjunto Comercial/Sala
3                   Apartamento
4            Casa de Condomínio
5                Prédio Inteiro
6                          Flat
7                    Loja/Salão
8       Galpão/Depósito/Armazém
9                Casa Comercial
10                 Casa de Vila
11               Terreno Padrão
12                  Box/Garagem
13                         Loft
14  Loja Shopping/ Ct Comercial
15                      Chácara
16        Loteamento/Condomínio
17                        Sítio
18                Pousada/Chalé
19                       Studio
20                        Hotel
21                    Indústria